---
- name: Playbook setup web server
  hosts: server_belajar
  become: yes
  become_method: sudo
  tasks:
    - name: Update repository
      ansible.builtin.apt:
        update_cache: true
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: Copy file html
      ansible.builtin.copy:
        src: ./web/
        dest: /var/www/html
    - name: connect to intranet server_belajar
      uri:
        url: "http://{{ item }}"
        status_code: 200
      with_items:
        - 192.168.56.102
        - 10.0.2.15

