---
- hosts: server_belajar
  become: true
  tasks:
    - name: Change user password arul
      routeros_command:
        commands:
          - /user set number=1 password=alung123

    - name: Change ssh port to 2222
      routeros_command:
        commands:
          - /ip service set port=2222 ssh

    - name: Change dns server
      routeros_command:
       commands:
         - /ip dns set servers=8.8.8.8
