---
- name: Test IOS Facts
  hosts: server_belajar
  tasks:
    - name: Gather IOS Facts
      ansible.builtin.apt:
        gather_subset: all
      register: all_subset
      ignore_errors: true
    - name: Print Subset All
      debug:
        var: all_subset
