---
- hosts: server_belajar
  become: true
  tasks:
    - name: Add Bridge
      routeros_command:
        commands:
          - /interface bridge add name=LAN

    - name: Add Bridge Port
      routeros_command:
        commands:
          - /interface bridge port add interface=ether2 bridge=LAN
          - /interface bridge port add interface=ether3 bridge=LAN
          - /interface bridge port add interface=ether4 bridge=LAN
          - /interface bridge port add interface=ether5 bridge=LAN

    - name: Add ip interface
      routeros_command:
        commands:
          - /ip address add address=192.168.2.1/24 interface=LAN

    - name: Add Pool
      routeros_command:
        commands:
          - /ip pool add name=sui ranges=192.168.1.2-192.168.1.254

    - name: Add DHCP Service
      routeros_command:
        commands:
          - /ip dhcp-server add name=sui interface=LAN address-pool=sui

    - name: Add Firewall
      routeros_command:
        commands:
          - /ip firewall nat chain=srcnat out-interface=ether1 action=masquerade

    - name: Add Radius
      routeros_command:
        commands:
          - /radius add service=login,ppp address=192.168.1.2 secret=arul123 authentication-port=1812 accounting-port=1813
