---
- name: package installation
  hosts: server_belajar
  tasks:
    - name: httpd package installation
      apt:
        name: httpd
        state: present
    - name: starting httpd service
      service: 
         name: httpd
         state: started
         enabled: yes