---
- name: Cisco show version example
  hosts: server_belajar
  gather_facts: false

  tasks:
    - name: run show version on the routers
      ios_command:
        commands: show run 
      register: output

    - name: print out
      debug: 
        var: output.stdout_lines