---
- hosts: server_belajar
  become: true
  tasks:
    - name: Add Script
      routeros_command:
        commands:
          - /system script add dont-require-permissions=no name=Backup_Daily owner=admin policy=ftp,reboot,read,write,policy,test,password,sniff,sensitive,romon source=
            "### Set local variables. Change the value between \"\" to reflect your environment. Do not delete quotation marks.
            :local ftpserver \"FTP-SERVER-FQDN_or_IP-ADDRESS\"
            :local username \"FTP-SERVER-USERNAME\"
            :local password \"FTP-SERVER-PASSWORD\"
             "
