---
- hosts: server_belajar
  become: true
  tasks:
    - name: find user
      routeros_command:
        commands:
          - /user :put [find name:{{data}}]

    - name: Change password
      routeros_command:
        commands:
          - /user set {{data}} password=alung123
